CREATE Database TollData;
USE TollData;

CREATE TABLE TollData.ROADS(
   state               VARCHAR(14) 
  ,name_of_facility    VARCHAR(74) 
  ,toll_id             INTEGER  
  ,operating_authority VARCHAR(97)
  ,from_location                VARCHAR(57) 
  ,to_location                  VARCHAR(46) 
  ,miles               NUMERIC(6,2) 
  ,rural_urban         VARCHAR(11) 
  ,kind                VARCHAR(72)
  ,Authority_Source    VARCHAR(38)
  ,Fee_Type            VARCHAR(7) 
  ,vehicle_fee         NUMERIC(5,2) 
  ,Truck_fee           NUMERIC(6,2) 
);


COMMIT;
USE TollData;
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Alabama','Foley Beach Express',4,'American Roads- LLC','AL 59 (in Foley)','AL 180 (in Orange Beach)',8.53,'Rural','Alabama Freedom Pass','None','Fixed',3.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('California','Seventeen Mile Drive',17,'Pebble Beach Company','Pacific Grove','Carmel',10.8,'Urban',NULL,'None','Fixed',10.25,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('California','Route 91 Express Lanes',18,'Orange County Transportation Authority','Orange/Riverside County Line','Highway 55',10,'Urban','FASTRAK/Title 21/Tiris','None','Fixed',1.55,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('California','Eastern Trans. Corridor (Routes 261- 241- & 133)',19,'CA Department of Trans; Orange County Trans Corridor Agencies','State Route 91','I-5 & State Route 133',24,'Urban','FASTRAK/Title 21/Tiris','None','Fixed',1.58,1.58);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('California','Foothill Trans. Corridor (Route 241)',20,'CA Department of Trans; Trans Corridor Agencies','I-5 San Clemente','State Route 241; Eastern Corridor',28,'Urban','FASTRAK/Title 21/Tiris','Section 129 (General Toll Progam)','Fixed',1.58,1.58);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('California','San Joaquin Hills Trans Corridor (Route 73)',21,'CA Department of Trans; Trans Corridor Agencies','Newport Beach','San Juan Capistrano',15,'Urban','FASTRAK/Title 21/Tiris','Section 129 (General Toll Progam)','Fixed',2.04,2.04);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('California','Route 125',23,'California Transportation Ventures- Inc.','State Route 905','State Route 54',10,'Urban','FASTRAK/Title 21/Tiris','Section 129 (General Toll Progam)','Fixed',0.85,1.70);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Colorado','Northwest Parkway',25,'Northwest Parkway Public Highway Authority','I-25- MP 228 in North Denver','96th Street (in City of Broomfield)',10,'Urban','Go Pass AVI and LPT','None (not a Federal-aid toll facility)','Fixed',3.80,3.80);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Colorado','E-470',26,'E-470 Public Highway Authority','I-25 & C-470; Douglas County','I-25 & Northwest Parkway; Adams County',47,'Urban','EXpress Toll and Liecnse Plate Toll (LPT)','None (not a Federal-aid toll facility)','Fixed',14.50,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Colorado','Pikes Peak Toll Road',299,'City of Colorado Springs operates under a Term Special Use Permit issued by the US Forest Service','Town of Cascade- US 24 west of Colorado Springs','Top of Pikes Peak Mountain -14- 110'' elevation',19,'Rural','Booth','None (not a Federal-aid toll facility)','Fixed',10.00,10.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Colorado','US 36 Bus Rapid Transit/HOV/Express Lanes',337,'Plenary Roads Denver','I-25','Interlocken',11,'Urban','EXpress Toll and Liecnse Plate Toll (LPT)','Section 166 (HOV/HOT lanes)','Fixed',1.25,176.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','Old Lebanon Road (Rd. 357)','Dyke Branch Road (Rd. 331)',7.74,'Urban','E-ZPass','Section 129 (General Toll Progam)','Fixed',1.00,4.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','Dyke Branch Road (Rd. 331)','Smyrna Toll (Rd. 150-B)',5.85,'Rural','E-ZPass','Section 129 (General Toll Progam)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','Smyrna Toll (Rd. 150-B)','North Smyrna Urban Limit',2.72,'Urban','E-ZPass','Section 129 (General Toll Progam)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','North Smyrna Urban Limit','C&D Canal Bridge',18.51,'Rural','E-ZPass','Section 129 (General Toll Progam)','Fixed',1.00,4.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','C&D Canal Bridge','Tybouts Corner',4.38,'Urban',NULL,'Section 129 (General Toll Progam)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','Tybouts Corner','US 13 North of Tybouts Corner',0.81,'Rural',NULL,'Section 129 (General Toll Progam)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Delaware','SR -1',29,'DE Dept of Trans','US 13 North of Tybouts Corner','I-95',4.81,'Rural',NULL,'Section 129 (General Toll Progam)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Beachline East (Central Florida Expressway)',47,'FL Turnpike Enterprise','SR 520','US 1 at Cocoa',15,'Rural/Urban','SunPass- EPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.25,0.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Beachline East (Central Florida Expressway)',47,'FL Turnpike Enterprise','SR 528','SR 405',6.8,'Rural/Urban',NULL,'Section 129 (General Toll Progam)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Beachline Expressway',48,'Central Florida Expway Auth (& FL Dept of Trans)','Boggy Creek Road','SR 520',22.46,'Rural/Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',1.00,1.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Beachline West',49,'FL Turnpike Enterprise','I-4 (SR 400)','Boggy Creek Road (SR 528A)',8.42,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.75,1.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Homestead Extension of Florida Turnpike (HEFT)',50,'FL Turnpike Enterprise','FL Trnpke MP 47 in Mirahar','US 1 in FL City',47.9,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',3.75,7.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Holland East-West Expressway',53,'Central Florida Expway Auth (& FL Dept of Trans)','FL Trnpke (SR 50 West)','SR 50 East Colonial Drive',22.36,'Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',0.25,0.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Sawgrass Expressway (SR 869)',54,'FL Turnpike Enterprise','FL Trnpke MP 71','I-75 / 595',21.66,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',2.00,4.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Central Florida Greenway (SR-417)',58,'Central Florida Expway Auth','Seminole/Orange Cnty Line','International Drive',33.4,'Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',0.50,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Daniel Webster - Western Beltway Part C',59,'Central Florida Expway Auth','US 441 (Orange Blossom Tr)','Seidel Rd',22.02,'Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',0.25,0.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Osceola Parkway',60,'Osceola Cnty- FL','Florida Turnpike','I-4 Interchange',12.4,'Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',0.75,0.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Polk Parkway (SR 570)',64,'FL Turnpike Enterprise','I-4 near Clark Rd extending E to SR 540','N to I-4 near Mt. Olive Rd',24.38,'Rural/Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',3.00,6.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','John Land - Apopka Expressway (SR 414)',303,'Central Florida Expway Auth','SR 429 (Western Beltway)','US 441 South',5,'Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',0.25,0.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','East-West (Dolphin) Expressway',45,'Miami-Dade Expway Auth (MDX)','I - 95  &  I - 395','HEFT',13.98,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.25,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Florida Turnpike - Mainline',46,'FL Turnpike Enterprise','Miami','Wildwood',266,'Rural','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',21.10,46.10);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','South Dade (Don Shula) Expressway',51,'Miami-Dade Expway Auth (MDX)','HEFT','Palmetto Expway',7.16,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.25,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Lee Roy Selmon Crosstown Expressway',52,'Tampa-Hillsborough Cnty Expwy Auth (FL Dept of Trans)','Gandy Boulevard','To I-75',14.17,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.50,1.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Miami Airport Expressway',55,'Miami-Dade Expway Auth (MDX)','I-95','Lejeune Rd (SR 953)',4.07,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',1.00,2.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Veterans Expressway (SR 589)',56,'FL Turnpike Enterprise','Courtney Campbell Causeway (SR 60)','North Dale Mabry',12.22,'Rural/Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',1.75,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Seminole Expressway',57,'FL Turnpike Enterprise','Northern Terminus of Eastern Beltway (SR 426-Aloma Ave)','I-4 West of US 192',17.45,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',2.00,4.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Southern Connector Extension',61,'FL Turnpike Enterprise','Central FL Greeneway','I-4 West of US 192',5.1,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.75,1.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Gratigny Parkway',62,'Miami-Dade Expway Auth (MDX)','Palmetto Expway','Northwest 119 Street at 27th Ave',5.37,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.50,1.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Snapper Creek Expressway',315,'Miami-Dade Expway Auth (MDX)','US1','SR 874',3.01,'Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.25,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Suncoast Parkway (SR 589)',63,'FL Turnpike Enterprise','Veterans near Van Dyke Rd (Hillsborogh Cnty)','US 96 (Hernando Cnty)',41.43,'Rural','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',3.00,6.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Wekiva Parkway',361,'Central Florida Expway Auth (& FL Dept of Trans)','CR 435/Mount Plymouth Road','West of Old McDonald Road',3.14,'Rural/Urban','SunPass- EPass- OPass- LeeWay','Section 129 (General Toll Progam)','Fixed',0.75,1.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Orchard Pond',362,'Orchard Pond Greenway- LLC','Old Bainbridge Road','Meridian Road',5.2,'Rural','SunPass- EPass- OPass- LeeWay',NULL,'Fixed',1.19,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Poinciana Parkway',363,'Osceola County Expressway Authority','US 17/92 and  Kinny Harmon Road','Cypress Parkway',9.7,'Rural','SunPass- EPass- OPass- LeeWay',NULL,'Fixed',2.25,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Goldenrod Road Extension',301,'Central Florida Expway Auth (& FL Dept of Trans)','Orlando International Airport','SR 551',2.7,'Urban','SunPass- EPass- OPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',0.50,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Florida','Mid-Bay Connector',32,'Mid-Bay Brdg Auth (& FL Dept of Transportation)','Mid-Bay Bridge','SR 85',11,'Rural/Urban','SunPass- EPass- LeeWay','None (not a Federal-aid toll facility)','Fixed',1.00,3.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Illinois','East-West Tollway (SR-56 Connector)',77,'IL State Hwy Toll Auth','I-88','SR 56',0.4,'Urban',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Illinois','Elgin O''Hare Expressway',364,'IL State Toll Highway Authority','Lake Street','Interstate 290',6.43,'Urban','IAG (E-Zpass- I-Pass- ETC.)','None (not a Federal-aid toll facility)','Fixed',2.10,6.40);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Louisiana','Avery Island',89,'Avery Island- Inc.','SR 329 Junction','Avery Island',1.5,'Rural',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Maine','Maine Turnpike (I-295)',90,'ME Trnpke Auth','South Portland','South Portland',0.4,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Maryland','Intercounty Connector (ICC) (MD 200)',99,'MD Transportation Authority (MDTA)','I-370','I-95/US 1',18.15,'Urban','E-ZPass','Section 129 (General Toll Progam)','Fixed',1.23,2.45);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Nevada','Valley of Fire Road',115,'NV State Park Div','W. Park Entrance (Valley of Fire St Park)','East Park Entrance',6.37,'Rural',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','F.E. Everett Turnpike',118,'NH Dept of Trans','Massachusetts State Line','F.E.E.T Exit 8 in Nashua',7.7,'Urban',NULL,NULL,'Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','F.E. Everett Turnpike',118,'NH Dept of Trans','F.E.E.T Exit 8 in Nashua','F.E.E.T. Exit 3 in Bedford',12.54,'Urban','E-Zpass','None (not a Federal-aid toll facility)','Fixed',1.75,0.90);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Spaulding Turnpike',120,'NH Dept of Transportation','Portsmouth Traffic Circle','S.T. Exit 5 in Dover',4.58,'Urban',NULL,'None (not a Federal-aid toll facility)','Fixed',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Spaulding Turnpike',120,'NH Dept of Transportation','S.T. Exit 5 in Dover','S.T. Exit 7 in Dover',4.52,'Urban','E-Zpass','None (not a Federal-aid toll facility)','Fixed',0.53,1.35);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Spaulding Turnpike',120,'NH Dept of Transportation','S.T. Exit 7 in Dover','S.T. Exit 9 in Dover',3.01,'Urban',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Spaulding Turnpike',120,'NH Dept of Transportation','S.T. Exit 9 in Dover','S.T. Exit 12 in Rochester',6.07,'Urban','E-Zpass','None (not a Federal-aid toll facility)','Fixed',0.53,1.35);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Spaulding Turnpike',120,'NH Dept of Transportation','S.T. Exit 12 in Rochester','S.T. Exit 16 in Rochester',4.59,'Urban',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Spaulding Turnpike',120,'NH Dept of Transportation','S.T. Exit 16 in Rochester','S.T. Exit 18 in Milton',10.49,'Rural/Urban',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Hampshire','Mt. Washington Auto Rd',121,'Mt. Washington Summit Rd Co','NH Route 16 in Greens Grant','Mt Washington Summit in Sargents Purchase',7.6,'Rural',NULL,'None (not a Federal-aid toll facility)','Dynamic',28.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','New Jersey Turnpike (Mainline)',152,'NJ Trnpke Auth','PA Trnpke Ext','Deepwater',14.26,'Rural','E-ZPass','None (not a Federal-aid toll facility)','Fixed',4.15,18.80);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','New Jersey Turnpike (Mainline)',152,'NJ Trnpke Auth','PA Trnpke Ext','Deepwater',37.69,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Fixed',4.15,21.90);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','New Jersey 495',153,'NJ Trnpke Auth','I-95','SR 3',0.78,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','Garden State Parkway',154,'NJ Trnpke Auth','Montvale','Cape May',19.89,'Rural',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','Garden State Parkway',154,'NJ Trnpke Auth','Montvale','Cape May',4.1,'Rural','E-ZPass','None (not a Federal-aid toll facility)','Fixed',8.25,61.35);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','Garden State Parkway',154,'NJ Trnpke Auth','Montvale','Cape May',148.41,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Fixed',8.25,47.90);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','Atlantic City Expressway',155,'South Jersey Trans Auth','Atlantic City','SR 42- Turnersville',12.72,'Rural','E-ZPass','None (not a Federal-aid toll facility)','Fixed',2.43,16.20);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New Jersey','Atlantic City Expressway',155,'South Jersey Trans Auth','Atlantic City','SR 42- Turnersville',31.48,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Fixed',2.43,16.20);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New York','Gov. Thomas E. Dewey Thruway Berkshire Section',187,'NY State Thruway Authority','I-87','I-90',5.6,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Dynamic',0.40,0.67);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New York','Gov. Thomas E. Dewey Thruway Gardenstate Parkway Connection',188,'NY State Thruway Authority','New Jersey Line','Spring Valley',2.4,'Urban',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New York','Whiteface Mountain Veterans Memorial Highway',189,'Olympic Regional Development Authority','Wilmington','Whiteface Mountain',5,'Rural',NULL,'None (not a Federal-aid toll facility)','Fixed',11.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('New York','Prospect Mountain Veterans Memorial Highway',190,'Department of Environmental  Conservation','US 9 (gate)','Top of Prospect Mountain',5.9,'Rural',NULL,'None (not a Federal-aid toll facility)','Fixed',10.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('North Carolina','Triangle Expressway',193,'North Carolina Turnpike Authority','I-40/NC 147 interchange- Durham County','NC-55 Bypass- Wake County',18.8,'Urban','NC Quick Pass (pre-paid transponder)
Bill by Mail (post-paid video bill)','Section 129 (General Toll Progam)','Dynamic',3.13,6.26);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','Indian Nation Turnpike',200,'OK Trnpke Auth','I-40 near Henryetta','US 70 near Hugo',105.2,'Rural','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.50,1.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','Muskogee Turnpike',201,'OK Trnpke Auth','Tulsa/Broken Arrow','I-40 near Weber Falls',53.1,'Rural','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.75,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','Cimarron Turnpike',202,'OK Trnpke Auth','I-35 East of Enid','Sand Springs',67.7,'Rural','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.75,0.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','John Kilpatrick Turnpike',203,'OK Trnpke Auth','I-40 between Mustang Road and Sara Road','OKC interchange of Turner Turnpike and I-35',25.3,'Urban','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.40,0.60);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','Creek Turnpike',204,'OK Trnpke Auth','I-44/SH 66 Sapulpa','US 412 - Admiral',34.4,'Urban','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.40,0.60);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','Chickasaw Turnpike',205,'OK Trnpke Auth','SH 1 near Ada','SH 7 - West of Sulphur',17.3,'Rural','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.75,0.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Oklahoma 5/','Cherokee Turnpike',206,'OK Trnpke Auth','US 412 at Locust Grove','US 412 - Arkansas Stateline',32.8,'Rural','Pike Pass','None (not a Federal-aid toll facility)','Fixed',0.50,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Pennsylvania','Amos Hutchinson Bypass',214,'PA Turnpike Commission','New Stanton (MP G0.0)','US 22 (MP G13.41)',13.41,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Fixed',1.64,2.45);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Pennsylvania','Toll Road 576 (Southern Beltway) Findlay Connector',311,'PA Turnpike Commission','Pittsburgh International Airport - I376 and PA60 (MP S1)','US Route 22 (MP S6)',4.16,'Rural','E-ZPass','None (not a Federal-aid toll facility)','Fixed',0.63,1.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Pennsylvania','Toll Road 576 (Southern Beltway) Findlay Connector',311,'PA Turnpike Commission','Pittsburgh International Airport - I376 and PA60 (MP S1)','US Route 22 (MP S6)',1.42,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Fixed',0.63,1.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Pennsylvania','Mon-Fayette Expressway',217,'PA Turnpike Commission','West Virginia Line (MP M0.00)','PA Rt 51 (MP M54.00)',31.66,'Urban','E-ZPass','None (not a Federal-aid toll facility)','Fixed',5.74,11.40);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Pennsylvania','Mon-Fayette Expressway',217,'PA Turnpike Commission','West Virginia Line (MP M0.00)','PA Rt 51 (MP M54.00)',17.18,'Rural','E-ZPass','None (not a Federal-aid toll facility)','Fixed',5.74,11.40);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Puerto Rico','Rafael Martínez Nadal Expressway (PR-20)',294,'Puerto Rico Highway and Transportation Authority','PR-1 (Guaynabo)','PR-199 Access (Guaynabo)',1.6,'Urban','Radio Frecuency ID (Auto Expresso)','None (not a Federal-aid toll facility)','Fixed',0.75,0.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Puerto Rico','Expreso Rio Hondo (PR-5)',295,'Metropistas','PR-199','PR-174',2.02,'Urban','Radio Frequency ID (Auto Expreso) 2 lanes','None (not a Federal-aid toll facility)','Fixed',0.35,0.65);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('South Carolina','Cross Island Parkway (US 278)',221,'South Carolina Deptartment of Transportation','US 278 Business','Palmetto Bay Road',7.5,'Rural','Palmetto Pass (transponder)','None (not a Federal-aid toll facility)','Fixed',0.75,1.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Dallas North Tollway',247,'North TX Tollway Authority (NTTA)','IH-35E','US 380',30.09,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.26,0.52);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Sam Houston Tollway - (East)',248,'Harris County Toll Road Authority','SH 3','North of Beltway Green Blvd',6.91,'Urban','Automatic Vehicle ID (AVI)',NULL,'Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Sam Houston Tollway - (NE)',248,'Harris County Toll Road Authority','Wallsvile Road','Old Humble Road',13,'Rural/Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Sam Houston Tollway  (West)',248,'Harris County Toll Road Authority','US 59 S','IH 45 N',26,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Sam Houston Tolway (SW Belt)',248,'Harris County Toll Road Authority','US 59 S','SH 288',11,'Urban','Automatic Vehicle ID (AVI)',NULL,'Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Sam Houston Tollway  (SE Belt)',248,'Harris County Toll Road Authority','SH 288','IH 45 S',10,'Urban','Automatic Vehicle ID (AVI)',NULL,'Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Hardy Toll Road',252,'Harris County Toll Road Authority','IH 45 N','IH 610 N',21.29,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Hardy Toll Road - Airport Connector',252,'Harris County Toll Road Authority','Hardy Tollroad','JFK Blvd',2.73,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.20,2.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Westpark Tollway',253,'Harris County Toll Road Authority','IH 610 W','Fort Bend County Line',13.02,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Westpark Tollway - Fort Bend County',253,'Fort Bend County Toll Road Authority','FM 1464','GP 99',6,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',0.65,1.30);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Fort Bend Parkway',257,'Harris County Toll Road Authority','Sam Houston Tollway Southwest','US 90A',2.44,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Fort Bend Parkway - Fort Bend County',257,'Fort Bend County Toll Road Authority','BW 8','SH 6',6.2,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',0.40,0.80);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','President George Bush Turnpike',254,'North TX Tollway Authority (NTTA)','Belt Line Road','SH 78',29.73,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.26,0.52);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','President George Bush Turnpike - Western Extension',254,'North TX Tollway Authority (NTTA)','SH 183','IH 20',11.84,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.26,0.52);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','President George Bush Turnpike - Eastern Extension',254,'North TX Tollway Authority(NTTA)','SH 78','IH 30',9.92,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.26,0.52);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Camino Colombia',255,'Texas Department of Transportation','IH 35','FM 1472',22.5,'Rural','Automatic Vehicle ID (AVI)','Section 129 (General Toll Progam)','Fixed',3.00,9.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','183-A',256,'Central Texas Regional Mobility Authority','SH45','South of San Gabriel Pkwy in Leander',9.5,'Urban','All Electronic Tolling (with Video Tolling)','Section 129 (General Toll Progam)','Fixed',0.41,0.82);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas 5/','SH 45 N',258,'Texas Department of Transportation','US 183','SH 130',12.8,'Urban','All Electronic AVI with pay by mail video tolling','Section 129 (General Toll Progam)','Fixed',0.71,1.42);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas 5/','SH 45 SE',259,'Texas Department of Transportation','US 183','IH 35',7,'Urban','All Electronic AVI with pay by mail video tolling','Section 129 (General Toll Progam)','Fixed',0.69,1.38);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH 130',260,'Texas Department of Transportation','IH35 N or Georgetown','US 183 S of ABIA',49,'Rural','All Electronic AVI with pay by mail video tolling','Section 129 (General Toll Progam)','Fixed',0.48,0.96);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Toll 49',261,'Northeast Texas Regional Mobility Authority (NETRMA)','SH 155','US 69',25.56,'Rural','All Electronic AVI with pay by mail video tolling','Section 129 (General Toll Progam)','Fixed',0.37,1.48);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Sam Rayburn Tollway',262,'North TX Tollway Authority (NTTA)','Denton Tap','US 75',25.46,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.26,0.52);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas 5/','Loop 1',263,'Texas Department of Transportation','Parmer Lane','SH 45',4,'Urban','All Electronic AVI with pay by mail video tolling','Section 129 (General Toll Progam)','Fixed',0.71,1.42);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Chisholm Trail Parkway',321,'North TX Tollway Authority (NTTA)','IH 30','US 67',28.6,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.29,0.58);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','DFW Connector',323,'Texas Department of Transportation','SH 121/SH 114','DFW International Airport',4.1,'Urban','All Electronic AVI with pay by mail video tolling','None (not a Federal-aid toll facility)','Fixed',0.70,1.34);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH99 (Grand Parkway)',324,'Texas Department of Transportation','IH 10','FM 1405 (Fisher Road)',8,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.56,1.12);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH99 (Grand Parkway)',324,'Texas Department of Transportation','IH 10','US 290',15.2,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.44,0.88);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH99 (Grand Parkway)',324,'Texas Department of Transportation','US 290','US 59',38.4,'Urban','Automatic Vehicle ID (AVI) & video enforcement','None (not a Federal-aid toll facility)','Fixed',0.44,0.88);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH99 (Grand Parkway)',324,'Fort Bend Grand Parkway Toll Road Authority','US 59','IH 10',12.1,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',0.35,0.70);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH 130 Seg 5/6',327,'SH 130 Concession Company and Texas Department of Transportation','US 183 S of ABIA','IH 10',41,'Rural','All Electronic AVI with pay by mail video tolling','None (not a Federal-aid toll facility)','Fixed',0.75,1.44);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Loop 375 (Cesar Chavez Managed Lanes)',328,'Camino Real Regional Mobility Authority','US 54','Zaragoza Road',8.9,'Urban','All Electronic AVI with pay by mail video tolling','None (not a Federal-aid toll facility)','Fixed',0.41,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH 550',330,'Cameron County Regional Mobility Authority','0.5 mi. east of FM 1847','SH 48',7.1,'Urban','All Electronic AVI with pay by mail video tolling','None (not a Federal-aid toll facility)','Fixed',0.50,2.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Manor Expressway',331,'Central Texas Regional Mobility Authority','US 183','Springdale Road',1.2,'Urban','All Electronic Tolling (with Video Tolling)','Section 129 (General Toll Progam)','Fixed',0.56,0.56);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Manor Expressway',331,'Central Texas Regional Mobility Authority','Springdale Road','Parmer Lane',5,'Urban','All Electronic Tolling (with Video Tolling)','Section 129 (General Toll Progam)','Fixed',0.56,1.12);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','US 59 (Southwest Freeway) HOV/HOT lane',343,'Metropolitan Transit Authority of Harris County','Smith Street on Spur 527','W. Airport',14.3,'Urban','EZ Tag- METRO Toll Tag','Section 166 (HOV/HOT lanes)','Fixed',1.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','US 59 (Eastex Freeway) HOV/HOT lane',344,'Metropolitan Transit Authority of Harris County','Frankllin','Loop 494',20.2,'Urban','EZ Tag- METRO Toll Tag','Section 166 (HOV/HOT lanes)','Fixed',1.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','US 290 (Northwest Freeway) HOV/HOT lane',345,'Metropolitan Transit Authority of Harris County','Northwest Transit Center','East of FM 1960',13.5,'Urban','EZ Tag- METRO Toll Tag','Section 166 (HOV/HOT lanes)','Fixed',1.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH 249 Tomball Tollway',348,'Harris County Toll Road Authority','Spring-Cypress Rd','FM 2920',5.64,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.50,3.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH 249 Direct Connector',350,'Harris County Toll Road Authority','SH249','Sam Houston Tollway',1.09,'Urban','Automatic Vehicle ID (AVI)','None (not a Federal-aid toll facility)','Fixed',1.20,2.75);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','SH 242 Direct Connector',349,'Montgomery County Toll Road Authority','SH242','IH45',1.91,'Urban','Automatic Vehicle ID (AVI)',NULL,'Fixed',0.25,0.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Texas','Mopac Express',355,'Central Texas Regional Mobility Authority','Parmer Lane','RM 2222',7,'Urban','All Electronic AVI with pay by mail video tolling','None (not a Federal-aid toll facility)','Fixed',0.25,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Utah','Adams Avenue Parkway',268,'Adams Avenue Parkway','I-84 (Exit 85)','5900 South',1,'Urban',NULL,'None (not a Federal-aid toll facility)','Fixed',1.00,1.50);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Vermont','Equinox Sky Line Drive',269,'Dr. Joe G. Davidson; Manchester','SR 7A - Sunderland','Mt. Equinox',5.4,'Rural',NULL,'None (not a Federal-aid toll facility)','Fixed',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Vermont','Mt. Mansfield Toll Road',270,'Mt. Mansfield Co- Inc.','SR 108','Mt. Mansfield',4.5,'Rural',NULL,'None (not a Federal-aid toll facility)','Fixed',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Vermont','Burke Mountain Toll Road',271,'Burke Mtn Recreation- Inc.','TH 7','Burke Mtn',2,'Rural',NULL,'None (not a Federal-aid toll facility)','Fixed',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Powhite Parkway Extension (SR 76)',276,'Virginia Department of Transportation','Chippenham Parkway','Route 288',9.44,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',0.25,1.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Powhite Parkway (SR 76)',276,'Richmond Metropolitan Authority','Chippenham Parkway (Route 150)','Interstate 195',3.26,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',0.70,0.80);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Downtown Expressway (SR 195)',277,'Richmond Metropolitan Authority','Interstate 95','Meadow Street',2.2,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',0.70,0.80);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Washington-Dulles Access and Toll Road/Route 267 (Hirst-Brault Expressway)',279,'Virginia Department of Transportation','Interstate 66','Route 28 (Dulles International Airport)',13.43,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',1.00,5.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Dulles Greenway (Hirst-Brault Expressway)',280,'Toll Road Investors Partnership II (TRIP II)','Route 7 & Route 15 Bypass at Leesburg','ECL Leesburg',0.69,'Urban',NULL,'None (not a Federal-aid toll facility)','Dynamic',0.00,0.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Dulles Greenway (Hirst-Brault Expressway)',280,'Toll Road Investors Partnership II (TRIP II)','ECL Leesburg','Route 659 - Belmont Ridge Road',4.79,'Rural','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',2.70,5.45);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Dulles Greenway (Hirst-Brault Expressway)',280,'Toll Road Investors Partnership II (TRIP II)','Route 659 - Belmont Ridge Road','Route 28 (at Dulles Airport)',7.05,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',3.15,6.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Chesapeake Expressway (SR 168)',281,'City of Chesapeake','Hillcrest Parkway','Gallbush Road',6.4,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','None (not a Federal-aid toll facility)','Fixed',3.00,4.00);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Virginia','Pocahontas Parkway/Airport Connector (Route 895)',282,'DBI Services- Inc.','Route 150 (Chippenham Parkway)','Interstate 295',10.12,'Urban','Automatic Vehicle ID (AVI) - E-ZPass','Section 129 (General Toll Progam)','Fixed',2.75,4.25);
INSERT INTO TollData.ROADS(state,name_of_facility,toll_id,operating_authority,from_location,to_location,miles,rural_urban,kind,Authority_Source,Fee_Type,vehicle_fee,Truck_fee) VALUES ('Washington','SR 167 - HOT Lanes',309,'Washington State Department of Transportation','Auburn- WA','Renton- WA',14.48,'Urban','Automatic Vehicle ID (AVI) - Good To Go','None (not a Federal-aid toll facility)','Fixed',9.00,0.00);
COMMIT;
